site_name: COMP423 Course Notes
theme:
  name: material

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Tutorials:
      - Go Setup: tutorials/go-setup.md